name: sleepscheduling
description: A new Flutter application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_core: ^0.5.0
  firebase_database: ^4.1.0
  firebase_auth: ^0.18.1+1
  flare_flutter: ^2.0.3
  shared_preferences: ^0.5.12
  percent_indicator: ^2.1.7+2
  flutter_icons: ^1.1.0
  fl_chart: ^0.11.1
  bottom_navy_bar: ^5.5.0
  url_launcher: ^5.7.2
  flutter_linkify: ^3.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
     - assets/images/logo.png
     - assets/space_demo.flr
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro.ttf

    - family:  MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf